# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:database.sqlite}
spring.datasource.driver-class-name=org.xerial.sqlitejdbc.Driver
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# Server Configuration
server.port=${SERVER_PORT:5000}
