server.port=5000
spring.datasource.url=jdbc:sqlite:/data/database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Multi-part for large uploads if needed
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
